version: '3'
services:
  user-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    image: userapp # Specify the image name here
    ports:
      - "3000:3000"
    volumes:
      - ./user-app:/usr/src/app
    environment:
      - DATABASE_URL=${DATABASE_URL}

  bank-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.bank
    image: bankapp  # Specify the image name here
    ports:
      - "3001:3001"
    volumes:
      - ./bank-app:/usr/src/app
    environment:
      - DATABASE_URL=${DATABASE_URL}

  bank-webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.webhook
    image: webhook  # Specify the image name here
    ports:
      - "3002:3002"
    volumes:
      - ./bank-webhook:/usr/src/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
