# docker-compose.yml

version: '3'
services:
  user-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    ports:
      - "3000:3000"
    volumes:
      - ./user-app:/usr/src/app
    environment:
      - NODE_ENV=development

  bank-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.bank
    ports:
      - "3001:3001"
    volumes:
      - ./bank-app:/usr/src/app
    environment:
      - NODE_ENV=development

  bank-webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.webhook
    ports:
      - "3002:3002"
    volumes:
      - ./bank-webhook:/usr/src/app
    environment:
      - NODE_ENV=development
